// Curated S&P 500 starter universe. ~250 well-known constituents. The full
// 500 can be substituted by replacing this array with the live list from
// e.g. https://www.slickcharts.com/sp500 or the official S&P methodology PDF.
// Keep tickers in EDGAR's preferred form (no dots — BRKB not BRK.B).

export type Sector =
  | "Technology"
  | "Communication Services"
  | "Consumer Discretionary"
  | "Consumer Staples"
  | "Energy"
  | "Financials"
  | "Health Care"
  | "Industrials"
  | "Materials"
  | "Real Estate"
  | "Utilities";

export type UniverseEntry = { ticker: string; sector: Sector };

export const SP500_UNIVERSE: UniverseEntry[] = [
  // Technology
  { ticker: "AAPL", sector: "Technology" },
  { ticker: "MSFT", sector: "Technology" },
  { ticker: "NVDA", sector: "Technology" },
  { ticker: "AVGO", sector: "Technology" },
  { ticker: "ORCL", sector: "Technology" },
  { ticker: "CRM", sector: "Technology" },
  { ticker: "ADBE", sector: "Technology" },
  { ticker: "CSCO", sector: "Technology" },
  { ticker: "AMD", sector: "Technology" },
  { ticker: "ACN", sector: "Technology" },
  { ticker: "INTC", sector: "Technology" },
  { ticker: "IBM", sector: "Technology" },
  { ticker: "QCOM", sector: "Technology" },
  { ticker: "NOW", sector: "Technology" },
  { ticker: "AMAT", sector: "Technology" },
  { ticker: "INTU", sector: "Technology" },
  { ticker: "PANW", sector: "Technology" },
  { ticker: "LRCX", sector: "Technology" },
  { ticker: "KLAC", sector: "Technology" },
  { ticker: "MU", sector: "Technology" },
  { ticker: "ADI", sector: "Technology" },
  { ticker: "FTNT", sector: "Technology" },
  { ticker: "ROP", sector: "Technology" },
  { ticker: "APH", sector: "Technology" },
  { ticker: "GLW", sector: "Technology" },
  { ticker: "KEYS", sector: "Technology" },
  { ticker: "CTSH", sector: "Technology" },
  { ticker: "MCHP", sector: "Technology" },
  { ticker: "ON", sector: "Technology" },
  { ticker: "ANSS", sector: "Technology" },
  { ticker: "CDNS", sector: "Technology" },
  { ticker: "SNPS", sector: "Technology" },
  { ticker: "WDC", sector: "Technology" },
  { ticker: "STX", sector: "Technology" },
  { ticker: "HPQ", sector: "Technology" },
  { ticker: "HPE", sector: "Technology" },
  { ticker: "DELL", sector: "Technology" },
  { ticker: "NTAP", sector: "Technology" },

  // Communication Services
  { ticker: "GOOGL", sector: "Communication Services" },
  { ticker: "META", sector: "Communication Services" },
  { ticker: "NFLX", sector: "Communication Services" },
  { ticker: "DIS", sector: "Communication Services" },
  { ticker: "CMCSA", sector: "Communication Services" },
  { ticker: "VZ", sector: "Communication Services" },
  { ticker: "T", sector: "Communication Services" },
  { ticker: "TMUS", sector: "Communication Services" },
  { ticker: "EA", sector: "Communication Services" },
  { ticker: "CHTR", sector: "Communication Services" },
  { ticker: "WBD", sector: "Communication Services" },
  { ticker: "PARA", sector: "Communication Services" },
  { ticker: "FOX", sector: "Communication Services" },
  { ticker: "OMC", sector: "Communication Services" },
  { ticker: "IPG", sector: "Communication Services" },

  // Consumer Discretionary
  { ticker: "AMZN", sector: "Consumer Discretionary" },
  { ticker: "TSLA", sector: "Consumer Discretionary" },
  { ticker: "HD", sector: "Consumer Discretionary" },
  { ticker: "MCD", sector: "Consumer Discretionary" },
  { ticker: "NKE", sector: "Consumer Discretionary" },
  { ticker: "LOW", sector: "Consumer Discretionary" },
  { ticker: "SBUX", sector: "Consumer Discretionary" },
  { ticker: "BKNG", sector: "Consumer Discretionary" },
  { ticker: "TJX", sector: "Consumer Discretionary" },
  { ticker: "ABNB", sector: "Consumer Discretionary" },
  { ticker: "MAR", sector: "Consumer Discretionary" },
  { ticker: "GM", sector: "Consumer Discretionary" },
  { ticker: "F", sector: "Consumer Discretionary" },
  { ticker: "ORLY", sector: "Consumer Discretionary" },
  { ticker: "AZO", sector: "Consumer Discretionary" },
  { ticker: "ROST", sector: "Consumer Discretionary" },
  { ticker: "YUM", sector: "Consumer Discretionary" },
  { ticker: "CMG", sector: "Consumer Discretionary" },
  { ticker: "DHI", sector: "Consumer Discretionary" },
  { ticker: "LEN", sector: "Consumer Discretionary" },
  { ticker: "PHM", sector: "Consumer Discretionary" },
  { ticker: "RCL", sector: "Consumer Discretionary" },
  { ticker: "CCL", sector: "Consumer Discretionary" },
  { ticker: "NCLH", sector: "Consumer Discretionary" },
  { ticker: "BBY", sector: "Consumer Discretionary" },
  { ticker: "DPZ", sector: "Consumer Discretionary" },
  { ticker: "DRI", sector: "Consumer Discretionary" },
  { ticker: "EBAY", sector: "Consumer Discretionary" },
  { ticker: "ETSY", sector: "Consumer Discretionary" },
  { ticker: "GPC", sector: "Consumer Discretionary" },
  { ticker: "HAS", sector: "Consumer Discretionary" },

  // Consumer Staples
  { ticker: "WMT", sector: "Consumer Staples" },
  { ticker: "PG", sector: "Consumer Staples" },
  { ticker: "COST", sector: "Consumer Staples" },
  { ticker: "KO", sector: "Consumer Staples" },
  { ticker: "PEP", sector: "Consumer Staples" },
  { ticker: "MO", sector: "Consumer Staples" },
  { ticker: "PM", sector: "Consumer Staples" },
  { ticker: "MDLZ", sector: "Consumer Staples" },
  { ticker: "CL", sector: "Consumer Staples" },
  { ticker: "TGT", sector: "Consumer Staples" },
  { ticker: "KMB", sector: "Consumer Staples" },
  { ticker: "GIS", sector: "Consumer Staples" },
  { ticker: "MNST", sector: "Consumer Staples" },
  { ticker: "KHC", sector: "Consumer Staples" },
  { ticker: "STZ", sector: "Consumer Staples" },
  { ticker: "SYY", sector: "Consumer Staples" },
  { ticker: "ADM", sector: "Consumer Staples" },
  { ticker: "KR", sector: "Consumer Staples" },
  { ticker: "HSY", sector: "Consumer Staples" },
  { ticker: "K", sector: "Consumer Staples" },
  { ticker: "CAG", sector: "Consumer Staples" },
  { ticker: "CPB", sector: "Consumer Staples" },
  { ticker: "TSN", sector: "Consumer Staples" },
  { ticker: "HRL", sector: "Consumer Staples" },
  { ticker: "EL", sector: "Consumer Staples" },
  { ticker: "CLX", sector: "Consumer Staples" },
  { ticker: "CHD", sector: "Consumer Staples" },
  { ticker: "MKC", sector: "Consumer Staples" },
  { ticker: "WBA", sector: "Consumer Staples" },

  // Energy
  { ticker: "XOM", sector: "Energy" },
  { ticker: "CVX", sector: "Energy" },
  { ticker: "COP", sector: "Energy" },
  { ticker: "SLB", sector: "Energy" },
  { ticker: "EOG", sector: "Energy" },
  { ticker: "MPC", sector: "Energy" },
  { ticker: "PSX", sector: "Energy" },
  { ticker: "VLO", sector: "Energy" },
  { ticker: "OXY", sector: "Energy" },
  { ticker: "HES", sector: "Energy" },
  { ticker: "DVN", sector: "Energy" },
  { ticker: "FANG", sector: "Energy" },
  { ticker: "BKR", sector: "Energy" },
  { ticker: "HAL", sector: "Energy" },
  { ticker: "KMI", sector: "Energy" },
  { ticker: "WMB", sector: "Energy" },
  { ticker: "TRGP", sector: "Energy" },
  { ticker: "OKE", sector: "Energy" },

  // Financials
  { ticker: "JPM", sector: "Financials" },
  { ticker: "BAC", sector: "Financials" },
  { ticker: "WFC", sector: "Financials" },
  { ticker: "MS", sector: "Financials" },
  { ticker: "GS", sector: "Financials" },
  { ticker: "C", sector: "Financials" },
  { ticker: "AXP", sector: "Financials" },
  { ticker: "BLK", sector: "Financials" },
  { ticker: "SPGI", sector: "Financials" },
  { ticker: "SCHW", sector: "Financials" },
  { ticker: "MMC", sector: "Financials" },
  { ticker: "CB", sector: "Financials" },
  { ticker: "PGR", sector: "Financials" },
  { ticker: "ICE", sector: "Financials" },
  { ticker: "USB", sector: "Financials" },
  { ticker: "PNC", sector: "Financials" },
  { ticker: "AON", sector: "Financials" },
  { ticker: "TFC", sector: "Financials" },
  { ticker: "CME", sector: "Financials" },
  { ticker: "COF", sector: "Financials" },
  { ticker: "BK", sector: "Financials" },
  { ticker: "TRV", sector: "Financials" },
  { ticker: "MET", sector: "Financials" },
  { ticker: "AIG", sector: "Financials" },
  { ticker: "ALL", sector: "Financials" },
  { ticker: "AFL", sector: "Financials" },
  { ticker: "PRU", sector: "Financials" },
  { ticker: "V", sector: "Financials" },
  { ticker: "MA", sector: "Financials" },
  { ticker: "FI", sector: "Financials" },
  { ticker: "PYPL", sector: "Financials" },
  { ticker: "STT", sector: "Financials" },
  { ticker: "FITB", sector: "Financials" },
  { ticker: "MTB", sector: "Financials" },
  { ticker: "HBAN", sector: "Financials" },
  { ticker: "RF", sector: "Financials" },

  // Health Care
  { ticker: "LLY", sector: "Health Care" },
  { ticker: "UNH", sector: "Health Care" },
  { ticker: "JNJ", sector: "Health Care" },
  { ticker: "MRK", sector: "Health Care" },
  { ticker: "ABBV", sector: "Health Care" },
  { ticker: "TMO", sector: "Health Care" },
  { ticker: "ABT", sector: "Health Care" },
  { ticker: "PFE", sector: "Health Care" },
  { ticker: "DHR", sector: "Health Care" },
  { ticker: "BMY", sector: "Health Care" },
  { ticker: "AMGN", sector: "Health Care" },
  { ticker: "GILD", sector: "Health Care" },
  { ticker: "ISRG", sector: "Health Care" },
  { ticker: "MDT", sector: "Health Care" },
  { ticker: "ELV", sector: "Health Care" },
  { ticker: "CI", sector: "Health Care" },
  { ticker: "REGN", sector: "Health Care" },
  { ticker: "VRTX", sector: "Health Care" },
  { ticker: "BSX", sector: "Health Care" },
  { ticker: "CVS", sector: "Health Care" },
  { ticker: "ZTS", sector: "Health Care" },
  { ticker: "HCA", sector: "Health Care" },
  { ticker: "HUM", sector: "Health Care" },
  { ticker: "BDX", sector: "Health Care" },
  { ticker: "SYK", sector: "Health Care" },
  { ticker: "EW", sector: "Health Care" },
  { ticker: "BIIB", sector: "Health Care" },
  { ticker: "IDXX", sector: "Health Care" },
  { ticker: "MCK", sector: "Health Care" },
  { ticker: "CAH", sector: "Health Care" },
  { ticker: "ZBH", sector: "Health Care" },
  { ticker: "ILMN", sector: "Health Care" },
  { ticker: "BAX", sector: "Health Care" },
  { ticker: "MTD", sector: "Health Care" },
  { ticker: "GEHC", sector: "Health Care" },
  { ticker: "A", sector: "Health Care" },
  { ticker: "RMD", sector: "Health Care" },
  { ticker: "DXCM", sector: "Health Care" },

  // Industrials
  { ticker: "CAT", sector: "Industrials" },
  { ticker: "GE", sector: "Industrials" },
  { ticker: "HON", sector: "Industrials" },
  { ticker: "RTX", sector: "Industrials" },
  { ticker: "BA", sector: "Industrials" },
  { ticker: "DE", sector: "Industrials" },
  { ticker: "ETN", sector: "Industrials" },
  { ticker: "ADP", sector: "Industrials" },
  { ticker: "LMT", sector: "Industrials" },
  { ticker: "GD", sector: "Industrials" },
  { ticker: "NOC", sector: "Industrials" },
  { ticker: "EMR", sector: "Industrials" },
  { ticker: "ITW", sector: "Industrials" },
  { ticker: "FDX", sector: "Industrials" },
  { ticker: "NSC", sector: "Industrials" },
  { ticker: "CSX", sector: "Industrials" },
  { ticker: "UNP", sector: "Industrials" },
  { ticker: "UPS", sector: "Industrials" },
  { ticker: "WM", sector: "Industrials" },
  { ticker: "RSG", sector: "Industrials" },
  { ticker: "MMM", sector: "Industrials" },
  { ticker: "JCI", sector: "Industrials" },
  { ticker: "OTIS", sector: "Industrials" },
  { ticker: "CARR", sector: "Industrials" },
  { ticker: "ROK", sector: "Industrials" },
  { ticker: "PAYX", sector: "Industrials" },
  { ticker: "FAST", sector: "Industrials" },
  { ticker: "DAL", sector: "Industrials" },
  { ticker: "UAL", sector: "Industrials" },
  { ticker: "AAL", sector: "Industrials" },
  { ticker: "LUV", sector: "Industrials" },
  { ticker: "ODFL", sector: "Industrials" },
  { ticker: "CHRW", sector: "Industrials" },
  { ticker: "GWW", sector: "Industrials" },
  { ticker: "PCAR", sector: "Industrials" },
  { ticker: "URI", sector: "Industrials" },
  { ticker: "BLDR", sector: "Industrials" },
  { ticker: "MAS", sector: "Industrials" },
  { ticker: "SWK", sector: "Industrials" },
  { ticker: "AOS", sector: "Industrials" },
  { ticker: "DOV", sector: "Industrials" },

  // Materials
  { ticker: "LIN", sector: "Materials" },
  { ticker: "SHW", sector: "Materials" },
  { ticker: "ECL", sector: "Materials" },
  { ticker: "FCX", sector: "Materials" },
  { ticker: "NUE", sector: "Materials" },
  { ticker: "NEM", sector: "Materials" },
  { ticker: "DOW", sector: "Materials" },
  { ticker: "DD", sector: "Materials" },
  { ticker: "PPG", sector: "Materials" },
  { ticker: "APD", sector: "Materials" },
  { ticker: "VMC", sector: "Materials" },
  { ticker: "MLM", sector: "Materials" },
  { ticker: "STLD", sector: "Materials" },
  { ticker: "PKG", sector: "Materials" },
  { ticker: "IP", sector: "Materials" },
  { ticker: "LYB", sector: "Materials" },
  { ticker: "BALL", sector: "Materials" },
  { ticker: "AVY", sector: "Materials" },
  { ticker: "EMN", sector: "Materials" },
  { ticker: "IFF", sector: "Materials" },
  { ticker: "ALB", sector: "Materials" },
  { ticker: "MOS", sector: "Materials" },
  { ticker: "CF", sector: "Materials" },
  { ticker: "FMC", sector: "Materials" },
  { ticker: "CE", sector: "Materials" },

  // Real Estate
  { ticker: "AMT", sector: "Real Estate" },
  { ticker: "PLD", sector: "Real Estate" },
  { ticker: "EQIX", sector: "Real Estate" },
  { ticker: "WELL", sector: "Real Estate" },
  { ticker: "PSA", sector: "Real Estate" },
  { ticker: "CCI", sector: "Real Estate" },
  { ticker: "SPG", sector: "Real Estate" },
  { ticker: "O", sector: "Real Estate" },
  { ticker: "DLR", sector: "Real Estate" },
  { ticker: "EXR", sector: "Real Estate" },
  { ticker: "AVB", sector: "Real Estate" },
  { ticker: "EQR", sector: "Real Estate" },
  { ticker: "VICI", sector: "Real Estate" },
  { ticker: "INVH", sector: "Real Estate" },
  { ticker: "ARE", sector: "Real Estate" },
  { ticker: "MAA", sector: "Real Estate" },
  { ticker: "UDR", sector: "Real Estate" },
  { ticker: "ESS", sector: "Real Estate" },
  { ticker: "REG", sector: "Real Estate" },
  { ticker: "KIM", sector: "Real Estate" },
  { ticker: "FRT", sector: "Real Estate" },
  { ticker: "BXP", sector: "Real Estate" },
  { ticker: "HST", sector: "Real Estate" },
  { ticker: "IRM", sector: "Real Estate" },

  // Utilities
  { ticker: "NEE", sector: "Utilities" },
  { ticker: "DUK", sector: "Utilities" },
  { ticker: "SO", sector: "Utilities" },
  { ticker: "AEP", sector: "Utilities" },
  { ticker: "EXC", sector: "Utilities" },
  { ticker: "ED", sector: "Utilities" },
  { ticker: "XEL", sector: "Utilities" },
  { ticker: "PEG", sector: "Utilities" },
  { ticker: "SRE", sector: "Utilities" },
  { ticker: "WEC", sector: "Utilities" },
  { ticker: "ES", sector: "Utilities" },
  { ticker: "AWK", sector: "Utilities" },
  { ticker: "DTE", sector: "Utilities" },
  { ticker: "ETR", sector: "Utilities" },
  { ticker: "PPL", sector: "Utilities" },
  { ticker: "AEE", sector: "Utilities" },
  { ticker: "CMS", sector: "Utilities" },
  { ticker: "CNP", sector: "Utilities" },
  { ticker: "EIX", sector: "Utilities" },
  { ticker: "FE", sector: "Utilities" },
  { ticker: "PCG", sector: "Utilities" },
  { ticker: "AES", sector: "Utilities" },
  { ticker: "EVRG", sector: "Utilities" },
  { ticker: "LNT", sector: "Utilities" },
  { ticker: "ATO", sector: "Utilities" },
  { ticker: "NRG", sector: "Utilities" },
];

export function getSectorMap(): Record<string, Sector> {
  const m: Record<string, Sector> = {};
  for (const e of SP500_UNIVERSE) m[e.ticker] = e.sector;
  return m;
}
